[workspace]
members = ["coordinator", "maker", "mobile/native", "crates/*"]
resolver = "2"

[patch.crates-io]
dlc-manager = { git = "https://github.com/get10101/rust-dlc", rev = "e0a4ee17414eb89389ae78a31de151fbc7c39022" }
dlc-messages = { git = "https://github.com/get10101/rust-dlc", rev = "e0a4ee17414eb89389ae78a31de151fbc7c39022" }
dlc = { git = "https://github.com/get10101/rust-dlc", rev = "e0a4ee17414eb89389ae78a31de151fbc7c39022" }
dlc-sled-storage-provider = { git = "https://github.com/get10101/rust-dlc", rev = "e0a4ee17414eb89389ae78a31de151fbc7c39022" }
p2pd-oracle-client = { git = "https://github.com/get10101/rust-dlc", rev = "e0a4ee17414eb89389ae78a31de151fbc7c39022" }
dlc-trie = { git = "https://github.com/get10101/rust-dlc", rev = "e0a4ee17414eb89389ae78a31de151fbc7c39022" }
simple-wallet = { git = "https://github.com/get10101/rust-dlc", rev = "e0a4ee17414eb89389ae78a31de151fbc7c39022" }
lightning = { git = "https://github.com/get10101/rust-lightning/", rev = "15d48d8243e05fbd198215c6a3a762d2bdc9f38b" }
lightning-background-processor = { git = "https://github.com/get10101/rust-lightning/", rev = "15d48d8243e05fbd198215c6a3a762d2bdc9f38b" }
lightning-block-sync = { git = "https://github.com/get10101/rust-lightning/", rev = "15d48d8243e05fbd198215c6a3a762d2bdc9f38b" }
lightning-net-tokio = { git = "https://github.com/get10101/rust-lightning/", rev = "15d48d8243e05fbd198215c6a3a762d2bdc9f38b" }
lightning-persister = { git = "https://github.com/get10101/rust-lightning/", rev = "15d48d8243e05fbd198215c6a3a762d2bdc9f38b" }
lightning-rapid-gossip-sync = { git = "https://github.com/get10101/rust-lightning/", rev = "15d48d8243e05fbd198215c6a3a762d2bdc9f38b" }
