[workspace]
members = ["coordinator", "maker", "mobile/native", "crates/*"]
resolver = "2"

[patch.crates-io]
dlc-manager = { git = "https://github.com/get10101/rust-dlc", rev = "304e85d" }
dlc-messages = { git = "https://github.com/get10101/rust-dlc", rev = "304e85d" }
dlc = { git = "https://github.com/get10101/rust-dlc", rev = "304e85d" }
dlc-sled-storage-provider = { git = "https://github.com/get10101/rust-dlc", rev = "304e85d" }
p2pd-oracle-client = { git = "https://github.com/get10101/rust-dlc", rev = "304e85d" }
dlc-trie = { git = "https://github.com/get10101/rust-dlc", rev = "304e85d" }
simple-wallet = { git = "https://github.com/get10101/rust-dlc", rev = "304e85d" }
lightning = { git = "https://github.com/get10101/rust-lightning/", rev = "be430fbc" }
lightning-background-processor = { git = "https://github.com/get10101/rust-lightning/", rev = "be430fbc" }
lightning-transaction-sync = { git = "https://github.com/get10101/rust-lightning/", rev = "be430fbc" }
lightning-net-tokio = { git = "https://github.com/get10101/rust-lightning/", rev = "be430fbc" }
lightning-persister = { git = "https://github.com/get10101/rust-lightning/", rev = "be430fbc" }
rust-bitcoin-coin-selection = { git = "https://github.com/p2pderivatives/rust-bitcoin-coin-selection" }
bdk = { git = "https://github.com/get10101/bdk", rev = "83fbc0cb471f8c377442d70bd6d68cea25d2221d" }
