[workspace]
members = ["coordinator", "maker", "mobile/native", "crates/*"]
resolver = "2"

[patch.crates-io]
dlc-manager = { git = "https://github.com/get10101/rust-dlc", rev = "f1627dbec11ac2ed062c841bd70d243c62743e6f" }
dlc-messages = { git = "https://github.com/get10101/rust-dlc", rev = "f1627dbec11ac2ed062c841bd70d243c62743e6f" }
dlc = { git = "https://github.com/get10101/rust-dlc", rev = "f1627dbec11ac2ed062c841bd70d243c62743e6f" }
dlc-sled-storage-provider = { git = "https://github.com/get10101/rust-dlc", rev = "f1627dbec11ac2ed062c841bd70d243c62743e6f" }
p2pd-oracle-client = { git = "https://github.com/get10101/rust-dlc", rev = "f1627dbec11ac2ed062c841bd70d243c62743e6f" }
dlc-trie = { git = "https://github.com/get10101/rust-dlc", rev = "f1627dbec11ac2ed062c841bd70d243c62743e6f" }
simple-wallet = { git = "https://github.com/get10101/rust-dlc", rev = "f1627dbec11ac2ed062c841bd70d243c62743e6f" }
lightning = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "91434931df734bb59307a30b847836b7752a1999" }
lightning-background-processor = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "91434931df734bb59307a30b847836b7752a1999" }
lightning-block-sync = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "91434931df734bb59307a30b847836b7752a1999" }
lightning-net-tokio = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "91434931df734bb59307a30b847836b7752a1999" }
lightning-persister = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "91434931df734bb59307a30b847836b7752a1999" }
lightning-rapid-gossip-sync = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "91434931df734bb59307a30b847836b7752a1999" }
