[workspace]
members = ["coordinator", "maker", "mobile/native", "crates/*"]
resolver = "2"

[patch.crates-io]
# We should usually track the `feature/ln-dlc-channels[-10101]` branch
dlc-manager = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "049388b" }
dlc-messages = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "049388b" }
dlc = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "049388b" }
dlc-sled-storage-provider = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "049388b" }
p2pd-oracle-client = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "049388b" }
dlc-trie = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "049388b" }
simple-wallet = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "049388b" }

# We should usually track the `split-tx-experiment[-10101]` branch
lightning = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "26db9546" }
lightning-background-processor = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "26db9546" }
lightning-transaction-sync = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "26db9546" }
lightning-net-tokio = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "26db9546" }
lightning-persister = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "26db9546" }

rust-bitcoin-coin-selection = { git = "https://github.com/p2pderivatives/rust-bitcoin-coin-selection" }
