[workspace]
members = ["coordinator", "maker", "mobile/native", "crates/*"]
default-members = [
  "coordinator",
  "maker",
  "mobile/native",
  "crates/bitmex-client",
  "crates/bitmex-stream",
  "crates/coordinator-commons",
  "crates/ln-dlc-node",
  "crates/orderbook-client",
  "crates/orderbook-commons",
  "crates/trade",
]

resolver = "2"

[patch.crates-io]
# We should usually track the `p2pderivatives/feature/ln-dlc-channels[-10101]` branch
dlc-manager = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "7a93489" }
dlc-messages = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "7a93489" }
dlc = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "7a93489" }
dlc-sled-storage-provider = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "7a93489" }
p2pd-oracle-client = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "7a93489" }
dlc-trie = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "7a93489" }
simple-wallet = { git = "https://github.com/p2pderivatives/rust-dlc", rev = "7a93489" }

# We should usually track the `p2pderivatives/split-tx-experiment[-10101]` branch
# Temporary fix: this fork allows us to access the channel monitor's channel_key_ids
lightning = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "698be7fb" }
lightning-background-processor = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "698be7fb" }
lightning-transaction-sync = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "698be7fb" }
lightning-net-tokio = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "698be7fb" }
lightning-persister = { git = "https://github.com/p2pderivatives/rust-lightning/", rev = "698be7fb" }

rust-bitcoin-coin-selection = { git = "https://github.com/p2pderivatives/rust-bitcoin-coin-selection" }

# Waiting for the next release
xtra = { git = "https://github.com/Restioson/xtra/", rev = "d98393a" }

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3
