[workspace]
members = ["coordinator", "maker", "mobile/native", "crates/*"]
resolver = "2"

[patch.crates-io]
dlc-manager = { git = "https://github.com/get10101/rust-dlc", rev = "d9a7a73" }
dlc-messages = { git = "https://github.com/get10101/rust-dlc", rev = "d9a7a73" }
dlc = { git = "https://github.com/get10101/rust-dlc", rev = "d9a7a73" }
dlc-sled-storage-provider = { git = "https://github.com/get10101/rust-dlc", rev = "d9a7a73" }
p2pd-oracle-client = { git = "https://github.com/get10101/rust-dlc", rev = "d9a7a73" }
dlc-trie = { git = "https://github.com/get10101/rust-dlc", rev = "d9a7a73" }
simple-wallet = { git = "https://github.com/get10101/rust-dlc", rev = "d9a7a73" }
lightning = { git = "https://github.com/get10101/rust-lightning/", rev = "5de4468d" }
lightning-background-processor = { git = "https://github.com/get10101/rust-lightning/", rev = "5de4468d" }
lightning-transaction-sync = { git = "https://github.com/get10101/rust-lightning/", rev = "5de4468d" }
lightning-net-tokio = { git = "https://github.com/get10101/rust-lightning/", rev = "5de4468d" }
lightning-persister = { git = "https://github.com/get10101/rust-lightning/", rev = "5de4468d" }
rust-bitcoin-coin-selection = { git = "https://github.com/p2pderivatives/rust-bitcoin-coin-selection" }
