[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bitcoin = "0.29"
clap = { version = "4", features = ["derive"] }
ln-dlc-node = { path = "../crates/ln-dlc-node" }
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
