name: "Build and push deliverables for latest main"

on:
  push:
    branches:
      - main

jobs:
  build_docker_image_for_latest_main:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/docker.yml
    with:
      tag: main

  build_and_release_ios_app_for_latest_main:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/ios.yml
    secrets: inherit
