name: Integration Test

on:
  push:
    branches:
      - "staging"

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Setup rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2.2.0
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install FFI bindings
        run: cargo install flutter_rust_bridge_codegen --version 1.62.1
      - name: Start containers
        run: |
          docker-compose up bitcoin electrs -d
          sleep 10 # We need to give docker a bit of time to startup

      - name: Test containers are up
        run: |
          curl -d '{"address":"bcrt1qylgu6ffkp3p0m8tw8kp4tt2dmdh755f4r5dq7s", "amount":"0.1"}' -H "Content-Type: application/json" -X POST http://localhost:3000/faucet

      - name: Generate FFI bindings
        run: just gen
      - name: Running cargo tests
        run: cargo test --features=system_tests
